---
- name: Eks Example Project
  hosts: localhost
  gather_facts: no
  vars:
    ProjectName: eks-example
    Environment: "{{ env | default('default') }}"
    State: "{{ state | default('present') }}"
  tasks:
    - name: Create the base networking stack
      cloudformation:
        stack_name: "{{ ProjectName }}-networking"
        state: "{{ State }}"
        region: ap-southeast-2
        disable_rollback: false
        template: "../templates/Networking.yml"
        template_parameters:
          ProjectName: "{{ ProjectName }}"
          Environment: "{{ Environment }}"
          VpcCidrBlock: 10.3.0.0/16
          PublicSubnetAZ1CidrBlock: 10.3.1.0/24
          PublicSubnetAZ2CidrBlock: 10.3.2.0/24
          PrivateSubnetAZ1CidrBlock: 10.3.11.0/24
          PrivateSubnetAZ2CidrBlock: 10.3.12.0/24
        tags:
          Stack: cloudformation-eks-example

    - name: Get networking stack information
      when: State == "present"
      cloudformation_info:
        stack_name: "{{ ProjectName }}-networking"
      register: output

    - debug:
        msg: "{{ output.cloudformation[ProjectName+'-networking'].stack_outputs }}"

    - name: Create an EFS for the EKS cluster
      cloudformation:
        stack_name: "{{ ProjectName }}-efs"
        state: "{{ State }}"
        region: ap-southeast-2
        disable_rollback: false
        template: "../templates/ElasticFileSystem.yml"
        template_parameters:
          ProjectName: "{{ ProjectName }}"
          Environment: "{{ Environment }}"
          Lifecycle: AFTER_7_DAYS
          EfsMountSubnet: "{{ network_stack_info.PublicSubnetAZ1 }}"
          SecurityGroups: "{{ network_stack_info.SharedSecurityGroup }}"
        tags:
          Stack: cloudformation-eks-example
      vars:
        network_stack_info: "{{ output['cloudformation'][ProjectName+'-networking']['stack_outputs'] }}"

    - name: Create EKS nodes and cluster
      cloudformation:
        stack_name: "{{ ProjectName }}-eks"
        state: "{{ State }}"
        region: ap-southeast-2
        disable_rollback: false
        template: "../templates/EKS.yml"
        template_parameters:
          ProjectName: "{{ ProjectName }}"
          Environment: "{{ Environment }}"
          SecurityGroups: "{{ network_stack_info.SharedSecurityGroup }}"
          Subnets: "{{ network_stack_info.PublicSubnetAZ1 }},{{ network_stack_info.PublicSubnetAZ2 }},{{ network_stack_info.PrivateSubnetAZ1 }},{{ network_stack_info.PrivateSubnetAZ2 }}"
        tags:
          Stack: cloudformation-eks-example
      vars:
        network_stack_info: "{{ output['cloudformation'][ProjectName+'-networking']['stack_outputs'] }}"

    # https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html
    - name: Create kubeconfig
      when: State == "present"
      command: "aws eks update-kubeconfig --name {{ ProjectName }}-{{ Environment }}-eks-cluster"

    - name: Check kubeconfig
      when: State == "present"
      command: "kubectl get svc"
      register: kubeconfig
    
    - debug:
        msg: "{{ kubeconfig.stdout_lines }}"

    - name: Create kube cluster admin service account
      when: State == "present"
      command: "kubectl apply -f ../kubernetes/eks-admin-service-account.yml"
    
    - name: Install metrics server pod
      when: State == "present"
      command: "../kubernetes/install-metrics-server-pod.sh"
    
    # https://docs.aws.amazon.com/eks/latest/userguide/dashboard-tutorial.html
    - name: Install GUI Dashboard
      when: State == "present"
      command: "kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta4/aio/deploy/recommended.yaml"
