AWSTemplateFormatVersion: 2010-09-09
Description: Redis Cache Example
Parameters:
  ProjectName:
    Type: String
    Description: The name of the project.
    Default: ExampleEFS
  Environment:
    Type: String
    Description: The environment which this template has been deployed in.
    Default: Testing
  Lifecycle:
    Type: String
    Description: How long a file stays inactive until it moves to slower but cheaper storage
    Default: AFTER_7_DAYS
  EfsMountSubnet:
    Type: String
    Description: The subnet in which the
  SecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: The list of SecurityGroupIds to associate with the EFS Mount. Max 5 Security Groups.

Resources:
  EFS:
    Type: AWS::EFS::FileSystem
    Properties: 
      Encrypted: false
      FileSystemTags: 
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
      LifecyclePolicies: 
        - TransitionToIA: !Ref Lifecycle
      PerformanceMode: generalPurpose
      ThroughputMode: bursting
    
  MountTarget:
    Type: AWS::EFS::MountTarget
    Properties: 
      FileSystemId: !Ref EFS
      SecurityGroups: !Ref SecurityGroups
      SubnetId: !Ref EfsMountSubnet

Outputs:
    EfsMountTarget: 
        Value: !Ref MountTarget
        Export:
            Name: !Sub "${ProjectName}-${Environment}-EfsMountTargetId"
    EfsMountIp: 
        Value: !GetAtt MountTarget.IpAddress
        Export:
            Name: !Sub "${ProjectName}-${Environment}-RedisPrimaryPort"
