AWSTemplateFormatVersion : 2010-09-09
Description : Webserver template in YAML
Parameters:
    ProjectName:
        Type: String
        Description: The name of the project
        Default: ExampleWebserverTemplate
    NetworkingProjectName:
        Type: String
        Description: The name of the networking project
        Default: ExampleNetworkingTemplate
    Environment:
        Type: String
        Description: The environment which this template has been deployed in
        Default: Example

Resources:
    ELBSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties: 
            GroupDescription : Allow all ingress traffic from any source associated with this security group
            VpcId: !ImportValue 
                        "Fn::Sub": "${NetworkingProjectName}-VPC"
            SecurityGroupIngress: 
                - IpProtocol : tcp
                  FromPort   : 443
                  ToPort     : 443
                  CidrIp     : !ImportValue 
                                    "Fn::Sub": "${NetworkingProjectName}-EIPNATAZ1CIDR"
            SecurityGroupEgress: 
                - IpProtocol : tcp
                  FromPort   : 0
                  ToPort     : 65535
                  CidrIp     : !ImportValue 
                                    "Fn::Sub": "${NetworkingProjectName}-EIPNATAZ1CIDR"
            Tags:
                - Key: Name
                  Value: "Inbound SSL security group"
    BaseWebserverSecurityGroupSelfReference : 
        Type : AWS::EC2::SecurityGroupIngress
        Properties : 
            GroupId : 
                Ref : ELBSecurityGroup
            IpProtocol : tcp
            FromPort   : 0
            ToPort     : 65535
            SourceSecurityGroupId : 
                Ref : ELBSecurityGroup
        DependsOn  : ELBSecurityGroup
                  
    LoadBalancer:
        Type: AWS::ElasticLoadBalancingV2::LoadBalancer
        Properties:
            LoadBalancerAttributes:
                # Closes front end connection after 90 seconds
                - Key: idle_timeout.timeout_seconds
                  Value: 90
            Name: PrivateLB1
            Scheme: internet-facing #[internet-facing,internal] are the valid values here
            SecurityGroups:
                - !Ref ELBSecurityGroup
            Subnets: 
                - !ImportValue
                    "Fn::Sub": "${NetworkingProjectName}-PrivateSubnetAZ1"
                - !ImportValue
                    "Fn::Sub": "${NetworkingProjectName}-PrivateSubnetAZ3"
            Tags:
                - Key: Name
                  Value: "LoadBalancer"
        DependsOn:
                - ELBSecurityGroup
                    
        
        